sudo: true
language: python
python:
- '3.6'
install:
- pip install pipenv
- pipenv install --dev
- pipenv run python -m pip install -e .
script:
- cd flask_project
- pipenv run pytest --cov=./ --show-progress ../tests